import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "@/provider/ConvexClientProvider";
import { Toaster } from "sonner";
import { GlobalStoreProvider } from "@/context/global-store";
import { ConvexQueryCacheProvider } from "convex-helpers/react/cache/provider";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" className={`${geist.variable}`}>
        <GlobalStoreProvider>
          <body>
            <Toaster position="top-center" richColors />
            <ConvexClientProvider>
              <ConvexQueryCacheProvider>{children}</ConvexQueryCacheProvider>
            </ConvexClientProvider>
          </body>
        </GlobalStoreProvider>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
